version: "3.8"
services:
  server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - database
  database:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookstoredb
      POSTGRES_USER: u
      POSTGRES_PASSWORD: p
    ports:
      - "5432:5432"
  server_test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - database

volumes:
  init.sql:
  data: